/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author gt618
 */
public class Pista extends javax.swing.JFrame {

    /**
     * Creates new form pista
     */
    
    public Pista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_carro1 = new javax.swing.JLabel();
        lbl_carro2 = new javax.swing.JLabel();
        lbl_carro3 = new javax.swing.JLabel();
        lbl_meta = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        lbl_pista_fondoEstatico = new javax.swing.JLabel();
        lbl_pista1 = new javax.swing.JLabel();
        lbl_pista2 = new javax.swing.JLabel();
        lbl_pista3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_carro1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/car1.gif"))); // NOI18N
        getContentPane().add(lbl_carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 35));

        lbl_carro2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/car2.gif"))); // NOI18N
        lbl_carro2.setPreferredSize(new java.awt.Dimension(90, 35));
        getContentPane().add(lbl_carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 39));

        lbl_carro3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/car3.gif"))); // NOI18N
        getContentPane().add(lbl_carro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 35));

        lbl_meta.setBackground(new java.awt.Color(255, 255, 255));
        lbl_meta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/finish.png"))); // NOI18N
        getContentPane().add(lbl_meta, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 80, 50, 120));

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/start.png"))); // NOI18N
        btn_inicio.setBorder(null);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        lbl_pista_fondoEstatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/Screenshot_20220628_084225.png"))); // NOI18N
        getContentPane().add(lbl_pista_fondoEstatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 512, 200));

        lbl_pista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/nima1-nimakrmanji.gif"))); // NOI18N
        getContentPane().add(lbl_pista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 480, 210));

        lbl_pista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/nima1-nimakrmanji.gif"))); // NOI18N
        getContentPane().add(lbl_pista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 200));

        lbl_pista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficos/nima1-nimakrmanji.gif"))); // NOI18N
        getContentPane().add(lbl_pista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, -60, 410, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioActionPerformed

    
    public JButton getBtn_inicio() {
        return btn_inicio;
    }

    public void setBtn_inicio(JButton btn_inicio) {
        this.btn_inicio = btn_inicio;
    }

    public JLabel getLbl_carro1() {
        return lbl_carro1;
    }

    public void setLbl_carro1(JLabel lbl_carro1) {
        this.lbl_carro1 = lbl_carro1;
    }

    public JLabel getLbl_carro2() {
        return lbl_carro2;
    }

    public void setLbl_carro2(JLabel lbl_carro2) {
        this.lbl_carro2 = lbl_carro2;
    }

    public JLabel getLbl_carro3() {
        return lbl_carro3;
    }

    public void setLbl_carro3(JLabel lbl_carro3) {
        this.lbl_carro3 = lbl_carro3;
    }

    public JLabel getLbl_meta() {
        return lbl_meta;
    }

    public void setLbl_meta(JLabel lbl_meta) {
        this.lbl_meta = lbl_meta;
    }

    public JLabel getLbl_pista_fondoEstatico() {
        return lbl_pista_fondoEstatico;
    }

    public void setLbl_pista_fondoEstatico(JLabel lbl_pista_fondoEstatico) {
        this.lbl_pista_fondoEstatico = lbl_pista_fondoEstatico;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicio;
    private javax.swing.JLabel lbl_carro1;
    private javax.swing.JLabel lbl_carro2;
    private javax.swing.JLabel lbl_carro3;
    private javax.swing.JLabel lbl_meta;
    private javax.swing.JLabel lbl_pista1;
    private javax.swing.JLabel lbl_pista2;
    private javax.swing.JLabel lbl_pista3;
    private javax.swing.JLabel lbl_pista_fondoEstatico;
    // End of variables declaration//GEN-END:variables
}
